#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Spec: 011 - Add database index on chat_history.user_id + project_id

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

# Server (FastAPI + PostgreSQL)
echo "Starting server..."
cd server && python main.py &
wait_for_service 8000 "Server"

# ============================================
# VERIFY MIGRATION
# ============================================

echo ""
echo "========================================"
echo "Verifying Alembic Migration Chain"
echo "========================================"

cd server
alembic current
echo ""
echo "Migration history (last 5):"
alembic history --format=chain 2>&1 | tail -10

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Server:  http://localhost:8000"
echo ""
echo "Migration:"
echo "  Run: cd server && alembic upgrade head"
echo "  Status: cd server && alembic current"
echo ""
